name: cross_ways
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_analytics: ^11.1.0
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  material_symbols_icons: ^4.2789.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/beachPhoto.jpg