// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJWGWlmr-Fh3ejgiO_hJyUAP256f_31yI',
    appId: '1:801033548083:web:a893ad4914100371f40e46',
    messagingSenderId: '801033548083',
    projectId: 'cross-ways-off',
    authDomain: 'cross-ways-off.firebaseapp.com',
    storageBucket: 'cross-ways-off.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUcLtTnjpoxbBvaoU0BcwPlTa1iwEjLvs',
    appId: '1:801033548083:android:9610000a2d96611af40e46',
    messagingSenderId: '801033548083',
    projectId: 'cross-ways-off',
    storageBucket: 'cross-ways-off.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxd9ZFaMEh9LBEITt8mCXk_FSx0JE-ojg',
    appId: '1:801033548083:ios:0f0561d90991b607f40e46',
    messagingSenderId: '801033548083',
    projectId: 'cross-ways-off',
    storageBucket: 'cross-ways-off.appspot.com',
    iosBundleId: 'com.example.crossWays',
  );
}
